name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    container: carlos1433/py-flask:latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -V
      

  test-job:
    runs-on: ubuntu-latest
    container: carlos1433/py-flask:latest
    steps:
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"
      - uses: actions/checkout@v3
      - run: flask --app myapp run

  deploy-job:
    runs-on: ubuntu-latest
    container: carlos1433/py-flask:latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado!"
      
