name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    container: carlos1433/py-flask:latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -V
      

  test-job:
    runs-on: ubuntu-latest
    container: carlos1433/py-flask:latest
    steps:
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"
      - uses: actions/checkout@v3
      - run: python3 myapp.py

  deploy-job:
    runs-on: ubuntu-latest
    container: carlos1433/py-flask:latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado!"
      - uses: actions/checkout@v3
      - run: firefox 127.0.0.1:8080
